# Use new container infrastructure to enable caching
sudo: false

language: go

go:
  - 1.7.x
  - 1.8.x

env:
  global: PROJECT_NAME="reco"

install:
- go get github.com/Masterminds/glide
- make clean dependencies

script:
- make test benchmark integration

notifications:
  slack:
    secure: FWI4CFnCtckIol8jA9VBm7Fy/+X7sAIgDKwc4UY2ufBIFAQekPmSl6YXMvCRKa4w4ndSjxGA1wd1YwB/tNUPxMkGDb1DCI2/E21aaxB0iwD/CM6OPlxpORiZ3mitB1rlb206D4dKzk5OsltikIkYK2s5PJ/w2Ax8ayMgpOYclt2myJLpxxPE5LDfBQ9DPyOpKyzdZuhRtC0hry/U8t/1zGcXkmXidzcUhfA67BR2jjUOKYvwnqgDauI2hXzDBtpTcsQ4t4nrLdq6YhUXBpPuUAvqBC9G9svztO+9OPMmz4bRHayCU1UUDgryEGA2eX8QSlYIwfRAI6Eg7Vx2UyDncItcX2KXU4o1vRLsVT6202UeTSLH1htip6gA8e+FPsMRgSpXT8peGCNmRI95FfX0Ovw6x4/8yVOIC2mndXBW0bScnUnsdwuCXvR7sfhnu8w7KCMSUyHWhpew+ndKhoU6sad650wlRqZQQobTzLI5fEravUYDsZjSXBCXifaotGph38bP+fmJaGqZimq7zogEgZaS55WOHz2zF+K7YUZ0+FjCXsv1EYx6m5XERXQT7kJpuIB2hBDHcaCIeAnr0gGDNZq5AWtDtUMBd0aBpFZW04Hj4GN+GcNLPQjVtiJlgdXwqaZkiNHcCc/t9T+50bCtPuXHLPmE4/bMhFy7u/FHlf8=

branches:
  only:
  - master
  - auto
  - try
  - rollup
  # IMPORTANT Ruby regex to match tags. Required, or travis won't trigger deploys when a new tag
  # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
  - /^v\d+\.\d+\.\d+.*$/

before_deploy:
  - ./ci/cross_compile.sh $TRAVIS_BRANCH

deploy:
  - provider: s3
    access_key_id:
      secure: "DSIFSNmyDMcRHt21V4EMd82IcMPvM0Ugla5O3bG9RcHkLoiBy2rlvCLFb/sMxL3hQZw8PMFilb3tQmtsEFLLvg0EHYomSKt33gRtcm22QmYTVo4ZKGOitErDqMMeJEHBeU4z1U6bxdnS0U0gI3bo8/lVIcEHspjACIFfAqUjtrSoPf5nhoMLTMQpUiJpR/a7voQJwuVS3zBvV67z3UDNBnw1H0SbqWt3OcmFZlRUWJR1pDpPi5jfsQjO9ctkqNv/ZQUUj5kjYHA1JohWVB60fEgaS2znaYzvTU8/UzfOhIMwR5Fxdcz13a6R8MMj+UkdYMtcChlVP1CXQbX1ND9Tn/hPK78C3P6lIFLPiV76PVQvE4RMi5ojG02UmcncNGuye/I/Gg4pdhWad42HmeFm1dx9JqlwrsG3mJriSYbHuUGFohtTH5i3n6sJn4Eya9Uw98SbL4WHAd9CXaMQvgNdML0MMXrhr58ClWN9G0xy09dHIR6PK9JHcyn+a7nMTYT3gBvC75jFLb3f0zVBIc9cqJL3vhtG0ippmL5DwdrgVaw7cPGpEd1Z6dVxIuyD7hGjIyMFZFz/p9yiuN3kszdGn3GJgQXNVBTcBdx5xQuDsT+mmdUsHzthqkNtIBO6ulI38G6i0q1rYTEmMCWRcl7JIHXlPiEVbVdY27Y12HOZE08="
    secret_access_key:
      secure: "Bl0GFUm7jerow67+P+IGEoYHcSN0yyjqis8GxtV/AQzGvEmZY00bOijYtriuHGX0NqT2JLxwhS8dy65E4karBopaRTQO84U6e2kG6SSRnjtKraEh9baDe1US/AjsFfqRTHi4A6bDsuJwZtU9r7LxSCalUfn0wqjBqPH328Lcof0Srn5op1oiLyR/oizDEw/8wxsVjANgJ0raOtWD3ObXDNMWqyc7tytZHrlVHbGX3rYhZEhCp5Iq1DOMytQc+QtHFqyn6aznZcy5v2QgmU02syZ6+qxLHDbGAMnyMXor/iz8OlpoZlK8xVyc4USB5I5/5rZkWQCx2ayhJZVUI6YpnEqFzsq0VvMjN1vwmAs73k3RoGP9weamjXNdaivjeT1UaiuKax44OzM2yzu6RFAAAvBXA2A2VuNJrF3VoU5BAjpmiqJVzQ254plAJAnyowrlm63N7bEo+9YUFTnDVqsaPq0uVgjdq+yh7Ibm/lMeJBUn6Rm3FJeCPZ4c4v0N7k/i4mdesg25Ehezmx71Np/6nVA5PlmGfigFGaT2Trfw9w1Cuc7Hmj5cF+46ew3w0oT2kcC+lPwlyJDe7gTT3x6xwfe5JKIF5GoXDc9d7G9Uqc69dw0/f8G75Vcd13Y+u1sfc/wuo7nagANpCRyDwMOy12Pl/Y3Avyak0FVlgTFYzEs="
    acl: public_read
    bucket: reconfigure.io
    local_dir: $TRAVIS_BUILD_DIR/dist
    upload-dir: reco/releases
    skip_cleanup: true
    on:
      branch: master
      repo: ReconfigureIO/reco
  - provider: s3
    access_key_id:
      secure: "DSIFSNmyDMcRHt21V4EMd82IcMPvM0Ugla5O3bG9RcHkLoiBy2rlvCLFb/sMxL3hQZw8PMFilb3tQmtsEFLLvg0EHYomSKt33gRtcm22QmYTVo4ZKGOitErDqMMeJEHBeU4z1U6bxdnS0U0gI3bo8/lVIcEHspjACIFfAqUjtrSoPf5nhoMLTMQpUiJpR/a7voQJwuVS3zBvV67z3UDNBnw1H0SbqWt3OcmFZlRUWJR1pDpPi5jfsQjO9ctkqNv/ZQUUj5kjYHA1JohWVB60fEgaS2znaYzvTU8/UzfOhIMwR5Fxdcz13a6R8MMj+UkdYMtcChlVP1CXQbX1ND9Tn/hPK78C3P6lIFLPiV76PVQvE4RMi5ojG02UmcncNGuye/I/Gg4pdhWad42HmeFm1dx9JqlwrsG3mJriSYbHuUGFohtTH5i3n6sJn4Eya9Uw98SbL4WHAd9CXaMQvgNdML0MMXrhr58ClWN9G0xy09dHIR6PK9JHcyn+a7nMTYT3gBvC75jFLb3f0zVBIc9cqJL3vhtG0ippmL5DwdrgVaw7cPGpEd1Z6dVxIuyD7hGjIyMFZFz/p9yiuN3kszdGn3GJgQXNVBTcBdx5xQuDsT+mmdUsHzthqkNtIBO6ulI38G6i0q1rYTEmMCWRcl7JIHXlPiEVbVdY27Y12HOZE08="
    secret_access_key:
      secure: "Bl0GFUm7jerow67+P+IGEoYHcSN0yyjqis8GxtV/AQzGvEmZY00bOijYtriuHGX0NqT2JLxwhS8dy65E4karBopaRTQO84U6e2kG6SSRnjtKraEh9baDe1US/AjsFfqRTHi4A6bDsuJwZtU9r7LxSCalUfn0wqjBqPH328Lcof0Srn5op1oiLyR/oizDEw/8wxsVjANgJ0raOtWD3ObXDNMWqyc7tytZHrlVHbGX3rYhZEhCp5Iq1DOMytQc+QtHFqyn6aznZcy5v2QgmU02syZ6+qxLHDbGAMnyMXor/iz8OlpoZlK8xVyc4USB5I5/5rZkWQCx2ayhJZVUI6YpnEqFzsq0VvMjN1vwmAs73k3RoGP9weamjXNdaivjeT1UaiuKax44OzM2yzu6RFAAAvBXA2A2VuNJrF3VoU5BAjpmiqJVzQ254plAJAnyowrlm63N7bEo+9YUFTnDVqsaPq0uVgjdq+yh7Ibm/lMeJBUn6Rm3FJeCPZ4c4v0N7k/i4mdesg25Ehezmx71Np/6nVA5PlmGfigFGaT2Trfw9w1Cuc7Hmj5cF+46ew3w0oT2kcC+lPwlyJDe7gTT3x6xwfe5JKIF5GoXDc9d7G9Uqc69dw0/f8G75Vcd13Y+u1sfc/wuo7nagANpCRyDwMOy12Pl/Y3Avyak0FVlgTFYzEs="
    acl: public_read
    bucket: reconfigure.io
    local_dir: $TRAVIS_BUILD_DIR/dist
    upload-dir: reco/releases
    skip_cleanup: true
    on:
      repo: ReconfigureIO/reco
      tags: true

