version: "{build}"

platform: x64

# Source Config
clone_folder: c:\gopath\src\github.com\ReconfigureIO\reco

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.9.1
  VERSION: master

init:
  - git config --global core.autocrlf input

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - choco install make
  - choco install nsis
  - choco install docker-compose
  - git clone https://github.com/ReconfigureIO/examples C:\reco-examples

build_script: 
  - if %APPVEYOR_REPO_TAG% equ true set VERSION=%APPVEYOR_REPO_TAG_NAME%
  - docker-compose run --rm go make clean dependencies
  - docker-compose run --rm go make test benchmark integration
  - docker-compose run go ./ci/cross_compile.sh %VERSION%

test_script:
  - make test

after_test:
  - dist\reco.exe version
  - C:\reco.exe check --source C:\reco-examples\addition
  - C:\reco.exe check --source C:\reco-examples\histogram
  - C:\reco.exe check --source C:\reco-examples\histogram-array
  - C:\reco.exe check --source C:\reco-examples\histogram-parallel
  - if %APPVEYOR_REPO_TAG% equ true set VERSION=%APPVEYOR_REPO_TAG_NAME%
  - copy C:\reco.exe C:\gopath\src\github.com\ReconfigureIO\reco\nsis
  - cd C:\gopath\src\github.com\ReconfigureIO\reco\nsis && "C:\Program Files (x86)\NSIS\makensis.exe" reco.nsi
  - appveyor PushArtifact C:\gopath\src\github.com\ReconfigureIO\reco\nsis\reco-%VERSION%.exe

deploy:
  - provider: S3
    access_key_id:
      secure: pnVvAHRFxuQal9FtXtj8kkMXTJWBEPQ0Pq6KbfPtSVI=
    secret_access_key:
      secure: l/N8Edoy4Lu5jGUCx7GYHfVHjrSxfd54J0BJRp1QizZS3zLHkIWTPgQ3xoc+LIUO
    bucket: reconfigure.io
    region: us-east-1
    unzip: false
    set_public: true
    folder: reco/releases
    on:
      appveyor_repo_tag: true
  - provider: S3
    access_key_id:
      secure: pnVvAHRFxuQal9FtXtj8kkMXTJWBEPQ0Pq6KbfPtSVI=
    secret_access_key:
      secure: l/N8Edoy4Lu5jGUCx7GYHfVHjrSxfd54J0BJRp1QizZS3zLHkIWTPgQ3xoc+LIUO
    bucket: reconfigure.io
    region: us-east-1
    unzip: false
    set_public: true
    folder: reco/releases
    on:
      branch: master

notifications:
  - provider: Email
    on_build_success: false

  - provider: Slack
    channel: #status
    incoming_webhook:
      secure: LbTv30cQKAAQHOmq90O6hFm1mjFRvZljYwtx7V00jq/HadB/IWPTwFzWFUOZMR6heHHMBxzGRmN8kRmqK5qw/q230fHqkJ4qZ+wUsiXz7VU=

